#批量添加和修改、删除front matter配置文件

# 需要批量处理的路径，docs文件夹内的文件夹  (数组，映射路径：path[0]/path[1]/path[2] ... )
path:
  - docs # 第一个成员必须是docs
  - Python
  - 12.Python工匠系列
#  - 04.更多

# 要删除的字段 (数组)
delete:
  # - tags

 # 要添加、修改front matter的数据 （front matter中没有的数据则添加，已有的数据则覆盖）
data:
  # sidebar: true
  author:
    name: piglei
    link: https://github.com/piglei/one-python-craftsman
  # author:
  #   name: xugaoyi
  #   link: https://github.com/xugaoyi

